display:
  default:
    display_options:
      title: Inicio
      header:
        area:
          content:
            value: '<h2 class="text-align-center">Explore recetas a través de cada tipo de ocasión, ingrediente y nivel de habilidad.</h2>'
