no_load_when_authenticated: true
no_load_when_session: true
no_load_content_types: {  }
ignore_admin_paths: true
ignore_hashes: true
ignore_ajax_links: true
ignore_file_ext: true
load_polyfill: true
selector: ''
url_patterns_to_ignore: ''
prefetch_only_paths: ''
allowed_domains: ''
enable_debug_mode: false
_core:
  default_config_hash: P-Tl0WcQCXKJey6r3MO_gbsRi-tGXdnjdW_G3NYITKE
